wandb_version: 1

aux_target_cols:
  value:
  - target_nomi_60
  - target_william_20
  - target
batch_size:
  value: 4000
dimensions:
  value:
  - 250
  - 100
  - 20
  - 50
  - 50
  - 50
dropout:
  value: 0.05171357728359599
feature_set:
  value: top_250_features_with_target_corr
initial_bn:
  value: true
learning_rate:
  value: 0.0026585052937522385
max_epochs:
  value: 10
model_name:
  value: AE
sample_4th_era:
  value: true
wd:
  value: 0.055436749528818025
