wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 400
  - 150
  - 20
dropout:
  value: 0.22666797184370263
feature_set:
  value: null
initial_bn:
  value: true
learning_rate:
  value: 0.0024736679837880932
max_epochs:
  value: 15
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.04978779714777178
