wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 1000
dimensions:
  value:
  - 750
  - 20
  - 20
  - 5
  - 20
  - 20
  - 20
dropout:
  value: 0.22300972199580835
feature_set:
  value: top_750_features_with_target_corr
initial_bn:
  value: false
learning_rate:
  value: 0.002105806050807422
max_epochs:
  value: 8
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.0589089402011454
