wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 10000
dimensions:
  value:
  - 750
  - 20
  - 20
  - 5
  - 20
  - 20
  - 20
dropout:
  value: 0.20187972481544533
feature_set:
  value: top_750_features_with_target_corr
initial_bn:
  value: true
learning_rate:
  value: 0.002621082847566097
max_epochs:
  value: 500
model_name:
  value: AEUP
sample_4th_era:
  value: true
wd:
  value: 0.04441110158881269
