wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1649633402
    t:
      1:
      - 1
      - 9
      - 55
      2:
      - 1
      - 9
      - 55
      3:
      - 2
      4: 3.9.5
      5: 0.12.14
      8:
      - 5
aux_target_cols:
  desc: null
  value: null
batch_size:
  desc: null
  value: 4000
dimensions:
  desc: null
  value:
  - 250
  - 20
  - 1
dropout:
  desc: null
  value: 0.22677035493945813
feature_set:
  desc: null
  value: top_250_features_with_target_corr
initial_bn:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.002264911296926259
max_epochs:
  desc: null
  value: 50
model_name:
  desc: null
  value: AUTO
sample_4th_era:
  desc: null
  value: true
wd:
  desc: null
  value: 0.044011416271371645
