wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 20
  - 20
  - 5
  - 20
  - 20
  - 20
dropout:
  value: 0.2813483866592536
feature_set:
  value: null
initial_bn:
  value: true
learning_rate:
  value: 0.002361600042335242
max_epochs:
  value: 5
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.05607914803439281
