# data config
feature_set: small
sample_4th_era: True
aux_target_cols: [ ]
batch_size: 1000
# model config
model_name: AEUP
#auto_dimensions: [38,4,1]
dimensions: [ 38,10, 5, 10, 38]
dropout: 0.001
initial_bn: True
learning_rate: 0.002
#kernel: 6
wd: 0.05
# trainer config
max_epochs: 1
