# data config
feature_set: small
sample_4th_era: True
aux_target_cols: [ ]
batch_size: 4000
# model config
model_name: AE
dimensions: [ 38, 20, 38, 50, 50, 50 ]
dropout: 0.001
initial_bn: True
learning_rate: 0.002
wd: 0.05
# trainer config
max_epochs: 1
