wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 750
  - 20
  - 20
  - 5
  - 20
  - 20
  - 20
dropout:
  value: 0.25845893430031003
feature_set:
  value: top_750_features_with_target_corr
initial_bn:
  value: true
learning_rate:
  value: 0.00226208698608663
max_epochs:
  value: 10
model_name:
  value: AEUP
sample_4th_era:
  value: true
wd:
  value: 0.045334836977037975
