wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 50
  - 20
  - 5
dropout:
  value: 0.2898391984529581
feature_set:
  value: null
initial_bn:
  value: true
learning_rate:
  value: 0.002173699973734583
max_epochs:
  value: 50
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.04253540433024832
