wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 50
  - 20
  - 5
dropout:
  value: 0.2074665071964028
feature_set:
  value: null
initial_bn:
  value: false
learning_rate:
  value: 0.0023322492155947875
max_epochs:
  value: 50
model_name:
  value: AEUP
sample_4th_era:
  value: true
wd:
  value: 0.05496958355427762
