wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.7.11
    start_time: 1651277023
    t:
      1:
      - 1
      - 9
      - 41
      2:
      - 1
      - 9
      - 41
      3:
      - 2
      - 7
      4: 3.7.11
      5: 0.12.11
      8:
      - 5
aux_target_cols:
  desc: null
  value: null
batch_size:
  desc: null
  value: 4000
dimensions:
  desc: null
  value:
  - 1050
  - 50
  - 20
  - 5
dropout:
  desc: null
  value: 0.22600892781151125
feature_set:
  desc: null
  value: null
initial_bn:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.002085709711196848
max_epochs:
  desc: null
  value: 50
model_name:
  desc: null
  value: AECONVPOOL
sample_4th_era:
  desc: null
  value: true
wd:
  desc: null
  value: 0.05475773310542989
