wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 50
  - 20
  - 5
dropout:
  value: 0.22600892781151125
feature_set:
  value: null
initial_bn:
  value: true
learning_rate:
  value: 0.002085709711196848
max_epochs:
  value: 50
model_name:
  value: AECONVPOOL
sample_4th_era:
  value: true
wd:
  value: 0.05475773310542989
