wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.7.11
    start_time: 1649604404
    t:
      1:
      - 1
      - 9
      - 41
      2:
      - 1
      - 9
      - 41
      3:
      - 2
      - 7
      4: 3.7.11
      5: 0.12.11
      8:
      - 5
aux_target_cols:
  desc: null
  value:
  - target_nomi_60
  - target_william_20
batch_size:
  desc: null
  value: 4000
dimensions:
  desc: null
  value:
  - 250
  - 20
  - 10
dropout:
  desc: null
  value: 0.2343657165237378
feature_set:
  desc: null
  value: small
initial_bn:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0020293790904989213
max_epochs:
  desc: null
  value: 2
model_name:
  desc: null
  value: BASE
sample_4th_era:
  desc: null
  value: true
wd:
  desc: null
  value: 0.08017450809824174
