wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 750
  - 20
  - 20
  - 5
  - 20
  - 20
  - 20
dropout:
  value: 0.2140025130625574
feature_set:
  value: top_750_features_with_target_corr
initial_bn:
  value: false
learning_rate:
  value: 0.0023403871316053917
max_epochs:
  value: 10
model_name:
  value: AEUP
sample_4th_era:
  value: true
wd:
  value: 0.05716346314788772
