wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 50
  - 20
  - 5
  - 500
  - 200
  - 10
dropout:
  value: 0.284762480898195
feature_set:
  value: null
initial_bn:
  value: false
learning_rate:
  value: 0.0024725713131450826
max_epochs:
  value: 50
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.05445454595546799
