wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 38
  - 20
  - 1
dropout:
  value: 0.2918877575407371
feature_set:
  value: small
initial_bn:
  value: true
learning_rate:
  value: 0.002305470102742687
max_epochs:
  value: 50
model_name:
  value: AUTO
sample_4th_era:
  value: true
wd:
  value: 0.0422334335216373
