wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 38
  - 20
  - 1
dropout:
  value: 0.2158784965870581
feature_set:
  value: small
initial_bn:
  value: false
learning_rate:
  value: 0.002834715593938004
max_epochs:
  value: 50
model_name:
  value: AUTO
sample_4th_era:
  value: true
wd:
  value: 0.0405129631657312
