wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 50
  - 20
  - 5
  - 950
  - 75
  - 10
dropout:
  value: 0.2033086216465153
feature_set:
  value: null
initial_bn:
  value: true
learning_rate:
  value: 0.002277142254521995
max_epochs:
  value: 50
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.04981133013472294
