wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 10000
dimensions:
  value:
  - 750
  - 20
  - 20
  - 5
  - 20
  - 20
  - 20
dropout:
  value: 0.2594238426023337
feature_set:
  value: top_750_features_with_target_corr
initial_bn:
  value: false
learning_rate:
  value: 0.0029434240036489336
max_epochs:
  value: 500
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.0474635536459884
