wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 750
  - 20
  - 20
  - 5
  - 20
  - 20
  - 20
dropout:
  value: 0.2894255154210823
feature_set:
  value: top_750_features_with_target_corr
initial_bn:
  value: true
learning_rate:
  value: 0.0022318642236701094
max_epochs:
  value: 500
model_name:
  value: AEUP
sample_4th_era:
  value: true
wd:
  value: 0.049763143403224595
