wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1649632308
    t:
      1:
      - 1
      - 9
      - 55
      2:
      - 1
      - 9
      - 55
      3:
      - 2
      - 23
      4: 3.9.5
      5: 0.12.14
      8:
      - 5
aux_target_cols:
  desc: null
  value: null
batch_size:
  desc: null
  value: 4000
dimensions:
  desc: null
  value:
  - 38
  - 20
  - 1
dropout:
  desc: null
  value: 0.25425885157230355
feature_set:
  desc: null
  value: small
initial_bn:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.002356266139116896
max_epochs:
  desc: null
  value: 20
model_name:
  desc: null
  value: AUTO
sample_4th_era:
  desc: null
  value: true
wd:
  desc: null
  value: 0.04424196772733729
