wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 50
  - 20
  - 5
  - 900
  - 150
  - 10
dropout:
  value: 0.26638446646140534
feature_set:
  value: null
initial_bn:
  value: false
learning_rate:
  value: 0.0022778084540507485
max_epochs:
  value: 50
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.05998925911121315
