wandb_version: 1

aux_target_cols:
  value:
  - target
batch_size:
  value: 4000
dimensions:
  value:
  - 250
  - 100
  - 50
  - 25
  - 20
  - 25
  - 50
  - 50
  - 50
dropout:
  value: 0.29979666268571836
feature_set:
  value: top_250_features_with_target_corr
initial_bn:
  value: true
learning_rate:
  value: 0.002344689024424587
max_epochs:
  value: 1000
model_name:
  value: AE
sample_4th_era:
  value: true
wd:
  value: 0.04192296303022716
