# data config
pca: null
feature_set: top_750_most_volatile_features
sample_4th_era: True
aux_target_cols: [ target_jerome_20 ]
batch_size: 5000
# model config
model_name: AEMLP
dimensions: [ 512, 1920, 1920, 1920, 1920, 1024 ]
dropout: 0.1955
initial_bn: True
learning_rate: 0.002604
wd: 0.07866
# trainer config
max_epochs: 9
