# data config
pca: null
feature_set: top_250_features_with_target
sample_4th_era: True
aux_target_cols: [ ]
batch_size: 4000
# model config
model_name: BASE
dimensions: [ 512, 1024, 512, 256 ]
dropout: 0.015
initial_bn: True
learning_rate: 0.0015
wd: 0.09
# trainer config
max_epochs: 10
