# data config
pca: null
feature_set: small
sample_4th_era: True
aux_target_cols: [ target_jerome_20 ]
batch_size: 5000
# model config
model_name: CAE
dimensions: [38, 10, 38,50]
kernel: 2
stride: 1
pool_kernel: 1
dropout: 0.1955
initial_bn: True
learning_rate: 0.002604
wd: 0.07866
# trainer config
max_epochs: 9
