# sweep configuration
method: bayes
metric:
  name: val/spearman
  goal: maximize
parameters:
  # data config
  pca:
    value: null
  feature_set:
    values:
      - top_750_features_with_target
      - top_100_most_volatile_features
      - top_250_most_volatile_features
      - top_500_most_volatile_features
      - full
  sample_4th_era:
    value: true
  aux_target_cols:
    values:
      - [ ]
      - [ target_nomi_60 ]
      - [ target_nomi_60, target_jerome_20 ]
      - [ target_nomi_60, target_jerome_20, target_jerome_60 ]
      - [ target_nomi_60, target_jerome_20, target_janet_20 ]
  batch_size:
    value: 5000
  # model config
  model_name:
    value: BASE
  dimensions:
    values:
      - [ 1536, 2048, 1536, 1024, 1024 ]
      - [ 2048, 2048, 1536, 1536, 1024, 1024 ]
  dropout:
    min: 0.15
    max: 0.28
  initial_bn:
    value: true
  learning_rate:
    min: 0.0015
    max: 0.0028
  wd:
    min: 0.02
    max: 0.1
  # trainer config
  max_epochs:
    value: 20
