# sweep configuration
method: bayes
metric:
  name: val/spearman
  goal: maximize
parameters:
  # data config
  pca:
    values: [ 0.85, 0.9, 0.95, 0.99, null]
  feature_set:
    value: full
  sample_4th_era:
    value: True
  aux_target_cols:
    value: [ ]
  batch_size:
    value: 5000
  # model config
  model_name:
    value: BASE
  dimensions:
    value: [ 1024, 1536, 1536, 1024 ]
  dropout:
    value: 0.15
  initial_bn:
    value: true
  learning_rate:
    value: 0.0015
  wd:
    value: 0.09
  # trainer config
  max_epochs:
    value: 10
