# sweep configuration
method: bayes
metric:
  name: val/spearman
  goal: maximize
parameters:
  # data config
  pca:
    value: null
  feature_set:
    value: full
  sample_4th_era:
    value: True
  aux_target_cols:
    value: [ ]
  batch_size:
    value: 5000
  # model config
  model_name:
    value: BASE
  dimensions:
    value: [ 1920, 1920, 1920, 960 ]
  dropout:
    min: 0.0
    max: 0.3
  initial_bn:
    values:
      - True
      - False
  learning_rate:
    min: 0.001
    max: 0.003
  wd:
    min: 0.01
    max: 0.1
  # trainer config
  max_epochs:
    value: 10
