# sweep configuration
method: bayes
metric:
  name: val/spearman
  goal: maximize
parameters:
  # data config
  pca:
    value: null
  feature_set:
    values: [ top_750_least_volatile_features, top_750_most_volatile_features, top_750_features_with_target, full ]
  sample_4th_era:
    value: True
  aux_target_cols:
    value: [ ]
  batch_size:
    value: 5000
  # model config
  model_name:
    value: BASE
  dimensions:
    value: [ 1536, 1536, 1536, 1024 ]
  dropout:
    value: 0.15
  initial_bn:
    value: true
  learning_rate:
    value: 0.0015
  wd:
    value: 0.09
  # trainer config
  max_epochs:
    value: 10
