# sweep configuration
method: bayes
metric:
  name: val/spearman
  goal: maximize
parameters:
  # data config
  pca:
    value: null
  feature_set:
    values:
      - full
      - top_750_most_volatile_features
  sample_4th_era:
    value: true
  aux_target_cols:
    values:
      - [ target_nomi_60 ]
      - [ target_jerome_20 ]
      - [ target_nomi_60, target_jerome_20 ]
      - [ target_nomi_60, target_jerome_20, target_jerome_60, target_janet_20 ]
  batch_size:
    value: 5000
  # model config
  model_name:
    value: AEMLP
  dimensions:
    values:
      - [ 256, 1920, 1920, 1920, 1920, 1024 ]
      - [ 512, 1920, 1920, 1920, 1920, 1024 ]
      - [ 1024, 1920, 1920, 1920, 1920, 1024 ]
  dropout:
    min: 0.15
    max: 0.22
  initial_bn:
    value: true
  learning_rate:
    min: 0.0014
    max: 0.0028
  wd:
    min: 0.04
    max: 0.1
  # trainer config
  max_epochs:
    value: 10
