# sweep configuration
method: bayes
metric:
  name: val/spearman
  goal: maximize
parameters:
  # data config
  pca:
    value: null
  feature_set:
    value: top_750_most_volatile_features
  sample_4th_era:
    value: true
  aux_target_cols:
    value: [ target_jerome_20 ]
  batch_size:
    value: 500
  # model config
  model_name:
    value: TMLP
  dimensions:
    value: [ 1920, 1920, 1920, 1024 ]
  dropout:
    min: 0.18
    max: 0.21
  initial_bn:
    value: true
  learning_rate:
    min: 0.002
    max: 0.0028
  wd:
    min: 0.06
    max: 0.1
  # transformer config
  num_enc_layers:
    value: 1
  num_dec_layers:
    value: 1
  # trainer config
  max_epochs:
    min: 8
    max: 10
