# sweep configuration
method: bayes
metric:
  name: val/spearman
  goal: maximize
parameters:
  # data config
  pca:
    value: null
  feature_set:
    value: top_750_most_volatile_features
  sample_4th_era:
    value: true
  aux_target_cols:
    value: [ target_jerome_20 ]
  batch_size:
    value: 5000
  # model config
  model_name:
    value: CAE
  dimensions:
    values:
      - [750, 300, 750,200]
      - [750, 500, 750,500]
      - [750, 400, 750, 400]
  dropout:
    min: 0.18
    max: 0.21
  initial_bn:
    value: true
  learning_rate:
    min: 0.002
    max: 0.0028
  wd:
    min: 0.06
    max: 0.1
  # transformer config
  num_enc_layers:
    value: 1
  num_dec_layers:
    value: 1
  # conv config
  kernel:
    min: 150
    max: 300
  stride:
    min: 1
    max: 5
  pool_kernel:
    min: 7
    max: 15
  # trainer config
  max_epochs:
    min: 8
    max: 10
