# sweep configuration
method: bayes
metric:
  name: val/spearman
  goal: maximize
parameters:
  # data config
  pca:
    values:
      - null
      - 0.95
      - 0.99
  feature_set:
    values:
      - top_250_features_with_target
      - top_500_features_with_target
      - top_100_most_volatile_features
      - top_250_most_volatile_features
      - top_500_most_volatile_features
      - top_100_least_volatile_features
      - top_250_least_volatile_features
      - top_500_least_volatile_features
      - small
      - medium
      - full
  sample_4th_era:
    values:
      - true
      - false
  aux_target_cols:
    values:
      - [ ]
      - [ target_nomi_60 ]
      - [ target_nomi_60, "target_jerome_20"]
  batch_size:
    values:
      - 2000
      - 3000
      - 4000
      - 5000
  # model config
  model_name:
    value: BASE
  dimensions:
    values:
      - [ 512, 1024, 512, 256 ]
      - [ 1024, 1536, 1024, 512 ]
      - [ 1536, 1536, 1536, 1024]
  dropout:
    min: 0.0
    max: 0.3
  initial_bn:
    values:
      - true
      - false
  learning_rate:
    min: 0.001
    max: 0.003
  wd:
    min: 0.01
    max: 0.1
  # trainer config
  max_epochs:
    value: 15
