wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_loss_aux
      5: 1
      6:
      - 1
    - 1: train_corr
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_corr
      5: 1
      6:
      - 1
    - 1: val/mae
      5: 1
      6:
      - 1
    - 1: val/payout
      5: 1
      6:
      - 1
    - 1: val/spearman
      5: 1
      6:
      - 1
    - 1: val/sharpe
      5: 1
      6:
      - 1
    - 1: train/mae
      5: 1
      6:
      - 1
    - 1: train/payout
      5: 1
      6:
      - 1
    - 1: train/spearman
      5: 1
      6:
      - 1
    - 1: train/sharpe
      5: 1
      6:
      - 1
    python_version: 3.7.11
    start_time: 1649631903
    t:
      1:
      - 1
      - 9
      - 41
      2:
      - 1
      - 9
      - 41
      3:
      - 2
      - 7
      4: 3.7.11
      5: 0.12.11
      8:
      - 5
aux_target_cols:
  desc: null
  value: null
batch_size:
  desc: null
  value: 4000
dimensions:
  desc: null
  value:
  - 38
  - 20
  - 1
dropout:
  desc: null
  value: 0.26786406036407484
feature_set:
  desc: null
  value: small
initial_bn:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.0026233561165974707
max_epochs:
  desc: null
  value: 20
model_name:
  desc: null
  value: AUTO
sample_4th_era:
  desc: null
  value: true
wd:
  desc: null
  value: 0.04472921895450165
