wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 50
  - 20
  - 5
dropout:
  value: 0.2804721283066586
feature_set:
  value: null
initial_bn:
  value: false
learning_rate:
  value: 0.0022992106386909884
max_epochs:
  value: 15
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.041611332536168694
