wandb_version: 1

aux_target_cols:
  value:
  - target_nomi_60
  - target_william_20
batch_size:
  value: 4000
dimensions:
  value:
  - 250
  - 20
  - 10
dropout:
  value: 0.2343657165237378
feature_set:
  value: small
initial_bn:
  value: false
learning_rate:
  value: 0.0020293790904989213
max_epochs:
  value: 2
model_name:
  value: BASE
sample_4th_era:
  value: true
wd:
  value: 0.08017450809824174
