wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 50
  - 20
  - 5
dropout:
  value: 0.2287264017681937
feature_set:
  value: null
initial_bn:
  value: true
learning_rate:
  value: 0.002464849473905407
max_epochs:
  value: 15
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.05820267336552139
