wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 250
  - 20
  - 1
dropout:
  value: 0.22677035493945813
feature_set:
  value: top_250_features_with_target_corr
initial_bn:
  value: false
learning_rate:
  value: 0.002264911296926259
max_epochs:
  value: 50
model_name:
  value: AUTO
sample_4th_era:
  value: true
wd:
  value: 0.044011416271371645
