wandb_version: 1

aux_target_cols:
  value:
  - target
batch_size:
  value: 4000
dimensions:
  value:
  - 250
  - 100
  - 50
  - 50
  - 50
  - 50
dropout:
  value: 0.28558798908777755
feature_set:
  value: top_750_features_with_target_corr
initial_bn:
  value: true
learning_rate:
  value: 0.0029700222481058745
max_epochs:
  value: 20
model_name:
  value: AE
sample_4th_era:
  value: true
wd:
  value: 0.0403725627848833
