wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 750
  - 20
  - 20
  - 5
  - 20
  - 20
  - 20
dropout:
  value: 0.2170663200695984
feature_set:
  value: top_750_features_with_target_corr
initial_bn:
  value: true
learning_rate:
  value: 0.002840525259321913
max_epochs:
  value: 500
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.048729091265529136
