wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 50
  - 20
  - 5
dropout:
  value: 0.22278929615606932
feature_set:
  value: null
initial_bn:
  value: false
learning_rate:
  value: 0.002353448113149829
max_epochs:
  value: 50
model_name:
  value: AECONVPOOL
sample_4th_era:
  value: true
wd:
  value: 0.05162029425422807
