wandb_version: 1

aux_target_cols:
  value:
  - target_nomi_60
  - target_william_20
batch_size:
  value: 4000
dimensions:
  value:
  - 38
  - 20
  - 38
  - 50
  - 50
  - 50
dropout:
  value: 0.24817769186770777
feature_set:
  value: small
initial_bn:
  value: true
learning_rate:
  value: 0.0025574220915302523
max_epochs:
  value: 2
model_name:
  value: AE
sample_4th_era:
  value: true
wd:
  value: 0.05065284146495748
