wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1651083475
    t:
      1:
      - 1
      - 9
      - 40
      - 55
      4: 3.9.5
      5: 0.12.14
      8:
      - 5
aux_target_cols:
  desc: null
  value: null
batch_size:
  desc: null
  value: 4000
dimensions:
  desc: null
  value:
  - 250
  - 5
  - 1
dropout:
  desc: null
  value: 0.26766720129382326
feature_set:
  desc: null
  value: top_250_features_with_target_corr
initial_bn:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.0029200835860795937
max_epochs:
  desc: null
  value: 50
model_name:
  desc: null
  value: AUTO
sample_4th_era:
  desc: null
  value: true
wd:
  desc: null
  value: 0.05395893507521705
