wandb_version: 1

aux_target_cols:
  value:
  - target_nomi_60
  - target_william_20
batch_size:
  value: 4000
dimensions:
  value:
  - 250
  - 20
  - 10
dropout:
  value: 0.08083407661540117
feature_set:
  value: small
initial_bn:
  value: true
learning_rate:
  value: 0.002973705516826587
max_epochs:
  value: 5
model_name:
  value: AE
sample_4th_era:
  value: true
wd:
  value: 0.054905019057848406
