wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1651264175
    t:
      1:
      - 1
      - 9
      - 41
      2:
      - 1
      - 9
      - 41
      3:
      - 2
      4: 3.7.11
      5: 0.12.11
      8:
      - 5
aux_target_cols:
  desc: null
  value: null
batch_size:
  desc: null
  value: 4000
dimensions:
  desc: null
  value:
  - 1050
  - 50
  - 20
  - 5
dropout:
  desc: null
  value: 0.2036594121188539
feature_set:
  desc: null
  value: null
initial_bn:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.002337921484602901
max_epochs:
  desc: null
  value: 10
model_name:
  desc: null
  value: AEUP
sample_4th_era:
  desc: null
  value: true
wd:
  desc: null
  value: 0.05055487849590217
