wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 50
  - 20
  - 5
dropout:
  value: 0.2976061414461484
feature_set:
  value: null
initial_bn:
  value: false
learning_rate:
  value: 0.0023388254021606833
max_epochs:
  value: 10
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.04327745663399842
