wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 100
  - 50
  - 10
dropout:
  value: 0.28104156979451994
feature_set:
  value: null
initial_bn:
  value: true
learning_rate:
  value: 0.0020336447416547552
max_epochs:
  value: 15
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.04133120631001987
