wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 100
  - 50
  - 10
dropout:
  value: 0.25935291780808256
feature_set:
  value: null
initial_bn:
  value: true
learning_rate:
  value: 0.002195116911577348
max_epochs:
  value: 15
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.05628191785892634
