wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 50
  - 20
  - 5
dropout:
  value: 0.20993213987146228
feature_set:
  value: null
initial_bn:
  value: true
learning_rate:
  value: 0.0020525285692258445
max_epochs:
  value: 10
model_name:
  value: AEUP
sample_4th_era:
  value: true
wd:
  value: 0.05316978292576704
