wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 20
  - 20
  - 5
  - 20
  - 20
  - 20
dropout:
  value: 0.20854503615963016
feature_set:
  value: null
initial_bn:
  value: true
learning_rate:
  value: 0.0029221077072467696
max_epochs:
  value: 5
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.0415903882838113
