wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 20
  - 20
  - 5
  - 20
  - 20
  - 20
dropout:
  value: 0.2891310604084332
feature_set:
  value: null
initial_bn:
  value: false
learning_rate:
  value: 0.0028704888594785357
max_epochs:
  value: 5
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.04138979880722308
