wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 100
  - 50
  - 10
dropout:
  value: 0.23386797036453533
feature_set:
  value: null
initial_bn:
  value: false
learning_rate:
  value: 0.0022636503728439505
max_epochs:
  value: 15
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.0463493318741134
