wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 50
  - 20
  - 5
  - 600
  - 225
  - 10
dropout:
  value: 0.2090199361544738
feature_set:
  value: null
initial_bn:
  value: true
learning_rate:
  value: 0.0021753602861695463
max_epochs:
  value: 50
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.04250065421955802
