wandb_version: 1

aux_target_cols:
  value:
  - target
batch_size:
  value: 4000
dimensions:
  value:
  - 250
  - 100
  - 50
  - 25
  - 5
  - 25
  - 50
  - 100
  - 250
dropout:
  value: 0.2928127396303118
feature_set:
  value: top_250_features_with_target_corr
initial_bn:
  value: true
learning_rate:
  value: 0.002316757084644093
max_epochs:
  value: 100
model_name:
  value: AE
sample_4th_era:
  value: true
wd:
  value: 0.04171495989499549
