wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 750
  - 20
  - 20
  - 5
  - 20
  - 20
  - 20
dropout:
  value: 0.29326093713102513
feature_set:
  value: top_750_features_with_target_corr
initial_bn:
  value: false
learning_rate:
  value: 0.002794365826345825
max_epochs:
  value: 50
model_name:
  value: AEUP
sample_4th_era:
  value: true
wd:
  value: 0.044826014603035993
