wandb_version: 1

aux_target_cols:
  value:
  - target
batch_size:
  value: 4000
dimensions:
  value:
  - 750
  - 500
  - 20
  - 50
  - 50
  - 50
dropout:
  value: 0.2828449147502625
feature_set:
  value: top_750_features_with_target_corr
initial_bn:
  value: false
learning_rate:
  value: 0.002573641863178284
max_epochs:
  value: 20
model_name:
  value: AE
sample_4th_era:
  value: true
wd:
  value: 0.043015978571900995
