wandb_version: 1

aux_target_cols:
  value:
  - target
batch_size:
  value: 4000
dimensions:
  value:
  - 250
  - 100
  - 50
  - 5
  - 50
  - 100
  - 250
dropout:
  value: 0.2328653522735508
feature_set:
  value: top_250_features_with_target_corr
initial_bn:
  value: false
learning_rate:
  value: 0.002781317236116535
max_epochs:
  value: 20
model_name:
  value: AE
sample_4th_era:
  value: true
wd:
  value: 0.04406488934179062
