wandb_version: 1

aux_target_cols:
  value:
  - target
batch_size:
  value: 4000
dimensions:
  value:
  - 250
  - 100
  - 50
  - 5
  - 50
  - 100
  - 250
dropout:
  value: 0.2493438087647392
feature_set:
  value: top_250_features_with_target_corr
initial_bn:
  value: true
learning_rate:
  value: 0.0026334135255356543
max_epochs:
  value: 20
model_name:
  value: AE
sample_4th_era:
  value: true
wd:
  value: 0.04024473619993296
