wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1651146873
    t:
      1:
      - 1
      - 9
      - 41
      2:
      - 1
      - 9
      - 41
      3:
      - 2
      4: 3.7.11
      5: 0.12.11
      8:
      - 5
aux_target_cols:
  desc: null
  value: null
batch_size:
  desc: null
  value: 300
dimensions:
  desc: null
  value:
  - 750
  - 20
  - 20
  - 5
  - 20
  - 20
  - 20
dropout:
  desc: null
  value: 0.23314104899595028
feature_set:
  desc: null
  value: top_750_features_with_target_corr
initial_bn:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0027043075874101613
max_epochs:
  desc: null
  value: 500
model_name:
  desc: null
  value: AECONV
sample_4th_era:
  desc: null
  value: true
wd:
  desc: null
  value: 0.058342253845187944
