wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 38
  - 20
  - 1
dropout:
  value: 0.21225192750242733
feature_set:
  value: small
initial_bn:
  value: false
learning_rate:
  value: 0.0022478233688336168
max_epochs:
  value: 20
model_name:
  value: AUTO
sample_4th_era:
  value: true
wd:
  value: 0.04315851180634834
