wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 1050
  - 100
  - 50
  - 20
dropout:
  value: 0.21341859157865808
feature_set:
  value: null
initial_bn:
  value: false
learning_rate:
  value: 0.0020067295982997132
max_epochs:
  value: 10
model_name:
  value: AECONV
sample_4th_era:
  value: true
wd:
  value: 0.05494567770307179
