wandb_version: 1

aux_target_cols:
  value: null
batch_size:
  value: 4000
dimensions:
  value:
  - 250
  - 5
  - 1
dropout:
  value: 0.27440536411188043
feature_set:
  value: top_250_features_with_target_corr
initial_bn:
  value: true
learning_rate:
  value: 0.0023584474081541898
max_epochs:
  value: 50
model_name:
  value: AUTO
sample_4th_era:
  value: true
wd:
  value: 0.05462683198757764
